### ISSUE TITLE
Make sure we know how to move a new journal from dev to prod servers.

### ISSUE THREAD

**Issue by relaxing** [tulibraries/ojs#4]

**Comment by anniekj** [comment]
Google doc with Mary Rose comments:
https://docs.google.com/document/d/18gxVDcwzURNihKR6PZBauo9bAr_gwAY0uH46YGgP2s8/edit

**Comment by khdelphine** [comment]
This involves the developers. However after the journal itself is set up, each new issue is built directly on the the prod server, without and any developer intervention.

**Comment by anniekj** [comment]
Just wanted to add a quick note to say that Mary Rose is fine with the dev URL being different than the production URL for the undergrad journal.

**Comment by khdelphine** [comment]
Great, that's one less thing to worry about! Thanks, Annie.

On Wed, Jul 6, 2016 at 3:26 PM, anniekj <notifications@github.com> wrote:

> Just wanted to add a quick note to say that Mary Rose is fine with the dev
> URL being different than the production URL for the undergrad journal.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tulibraries/ojs/issues/4#issuecomment-230880289>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AMIZn6P51xuqVJBDvahr8RQqFb3qXS9Yks5qTAF0gaJpZM4I7HER>
> .
>



-- 
Delphine Khanna, Head of Digital Library Initiatives
Temple University Library (http://library.temple.edu)
Samuel L. Paley Library, Room 113, 1210 Polett Walk, Philadelphia, PA 19122
Tel: 215-204-4768 | Fax: 215-204-5201 | Email: delphine@temple.edu
